### PR TITLE
more

### PR DESCRIPTION
**Pull request by isakube**
more

- [x] more
- [x] more
- [x] more
- [x] more
- [x] more
- [x] more

### CODE REVIEW

**Comment by Errorcrafter** [comment]
cool

**Review by Errorcrafter — APPROVED** [review]
i have no idea how to merge on mobile i think this is how you do it

**Comment by Errorcrafter** [comment]
wait im stupid, its a draft lmaoq

**Comment by isakube** [comment]
lmaoq

was gonna brainstorm more but eh whatev

**Comment by isakube** [comment]
ALSO originally i was gonna do a "this message wont appear lmao xd fart ssdddrreeeerrfgfgfhefgeghssg" but im not smart with JS :l

**Pull request merged**
